name: Test Terraform Module
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-consul-module:
    runs-on: ubuntu-latest
    services:
      vault:
        image: hashicorp/vault:latest
        ports:
          - 127.0.0.1:8200:127.0.0.1:8200
        env:
          THIS: that
#        options: >-
#          --opt1=2
#          --opt2 three
    steps:
      - uses: actions/checkout@v4
      - name: Install go module
        run: |
          cd test/basicconsultokenissuer
          go test
